version: '3'

services:
  concourse-db:
    image: postgres
    env_file: '.postgres.env'
    environment:
    - PGDATA=/database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [ node.role == manager ]

  concourse:
    image: concourse/concourse:4.2.2
    depends_on: [concourse-db]
    command: quickstart
    privileged: true
    ports: ["8080:8080"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    env_file: '.concourse.env'

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager ]
